#!/usr/bin/env python3
"""gate.py — the deterministic acceptance gate (R3). No LLM anywhere in here.

    python3 board-game/tools/gate.py <project_dir> --bill <bill.json>

Runs the cadcode build itself, then answers one question with numbers: is this
a thing that can actually be printed, in the piece count the game's rules
require? Everything downstream (the review panel, the human gates) is opinion;
this file is the part that cannot be talked out of a verdict.

Checks, in order — the first hard failure still lets the rest run so a repair
round sees every problem at once, not one per cycle:

  1. build      `cadcode/scripts/cad` compiles the source and exports
                STEP/STL + one STL per named part. A non-`info` warning from
                the CAD kernel (disconnected_bodies, collision, sliver,
                invalid_brep) is blocking.
  2. bill       every component the rules call for exists as a named part in
                the declared quantity, and no part exists that the bill never
                asked for. Matching is by name prefix, so a bill line
                {"name": "tile", "qty": 48} wants tile_01..tile_48.
  3. pieces     each named part is ONE connected watertight body. Together
                with the bill check above, this is what replaces the old
                pipeline's fusion detector: 48 loose tiles arriving as one
                continuous mat now shows up as a bill mismatch (one part where
                48 were asked for), and a part that is secretly two lumps
                shows up here. Counting connected bodies on the ASSEMBLED mesh
                is not a fusion test any more — parts placed touching in
                display position legitimately share faces and merge.
  4. envelope   every part fits the printer, compared against sorted extents
                so a tall part may simply be laid down. Measured per part in
                its own frame, never the assembly's bounding box, which is a
                display arrangement and prints nothing.
  5. printability  overhang share and bridge span per part, taking the BEST of
                the six axis-aligned orientations. A lid modelled resting on
                its box reads as a 58mm unsupported bridge that disappears the
                moment you flip it to print, so measuring as-modelled would
                fail parts that are perfectly printable.
  6. interference  do any two PLACED pieces claim the same space? Everything
                above measures one part alone, and so is blind to the defect
                where two parts that were never booleaned together are simply
                drawn overlapping — nothing errors, because nothing was ever
                unioned. See interference.py for why this is measured as shared
                volume rather than distance or vertex containment.
                A part that MOVES is only as good as its worst position, and the
                pose it was exported in is not evidence about any of the others,
                so a project may declare its moving parts in `motion.json` and
                the check sweeps each one through its stated range. What that
                file declares is the axis and the range — design facts from the
                brief — never which position is the bad one; finding that is the
                job being automated.
  7. slice      OrcaSlicer, once per DISTINCT shape rather than per instance —
                48 identical tiles are one slice, not 48. When the slicer env
                vars are unset, or `--no-slice` is passed, nothing is measured
                and that lands in `unmeasured` below rather than passing quietly.
  8. fit_checks the project's own fit_checks.py, generated by the builder from
                the brief's `## Interfaces`. Whoever builds the geometry writes
                the check against the geometry they built, which is the whole
                reason the old part-name-prefix checker kept reporting real
                features as absent.
  9. lint       graduated lessons. A lesson that has cost two builds stops
                being advice and becomes a line in here.

Thresholds in this file are code-tier: improve.py may propose changes to them
only through a PR, never by editing at runtime. An agent that can lower its
own bar does not have a bar.

A check that could not reach a verdict lands in `unmeasured`, and a pass with
a non-empty `unmeasured` is not the same object as a clean pass. It does not
fail the gate: pieces resting in contact legitimately merge in the assembled
mesh, so failing on it would be a false alarm on correct designs and the gate
would be routed around within a week. It is carried instead — into gate.json,
into the printed line, into QUEUE.json on the next `advance`, and into a
refusal from `pipeline_queue.py ship` that only a human can accept with a
stated reason. Absence of screening is not safety: a gate that answers "fine"
when it did not look is worse than no gate, so the fix is to make the silence
visible rather than to guess a verdict.

Writes <project>/gate.json and prints one line. Exit 0 = PASS, 1 = FAIL.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]
CADCODE = REPO_ROOT / "cadcode"
CAD_CLI = CADCODE / "scripts" / "cad"
VENV_PY = REPO_ROOT / ".venv" / "bin" / "python"

# interference.py is a sibling; gate.py is run by path from anywhere.
sys.path.insert(0, str(HERE))

# ---------------------------------------------------------------------------
# Thresholds — code tier. PR only.
# ---------------------------------------------------------------------------

# Bambu Lab P2S is 256x256x256mm nominal. The usable area is smaller than the
# advertised number (bed clips, exclusion zones near the edges), and a board
# game part parked at the very edge is exactly the part that fails at 3am on
# someone else's printer. The margin is the difference between "fits on paper"
# and "prints".
BED_X_MM = 256.0
BED_Y_MM = 256.0
BED_Z_MM = 256.0
BED_MARGIN_MM = 5.0

OVERHANG_FAIL_PCT = 50.0

# Local span, not area: a 16mm slot bridges fine, a 50mm unsupported ceiling
# sags. Measured as the inscribed-circle diameter of each down-facing patch.
BRIDGE_SPAN_MAX_MM = 25.0

# A connected body smaller than this is a tessellation artefact (a sliver
# triangle disconnected from its parent), not a game piece. Counting it as a
# component would turn a mesh defect into a phantom passing part.
MIN_BODY_VOLUME_MM3 = 20.0

CAD_WALL_CLOCK_S = 180.0

BLOCKING_SEVERITIES = ("warning", "error", "critical")


def usable_bed() -> tuple[float, float, float]:
    return (BED_X_MM - 2 * BED_MARGIN_MM,
            BED_Y_MM - 2 * BED_MARGIN_MM,
            BED_Z_MM - BED_MARGIN_MM)


# ---------------------------------------------------------------------------
# Source identity
# ---------------------------------------------------------------------------

def source_fingerprint(project: Path) -> str:
    """sha256 over the project's Python source, sorted by relative path.

    Borrowed from cadcode's own create-check: an unchanged source tree must
    never be silently re-verified as if something had been fixed. A repair
    round that reports success without changing a byte is a repair round that
    did nothing.
    """
    h = hashlib.sha256()
    files = [project] if project.is_file() else sorted(
        p for p in project.rglob("*.py")
        if ".input" not in p.parts and "__pycache__" not in p.parts)
    for p in files:
        h.update(str(p.relative_to(project if project.is_dir() else project.parent)).encode())
        h.update(p.read_bytes())
    return h.hexdigest()


# ---------------------------------------------------------------------------
# 1. Build
# ---------------------------------------------------------------------------

def run_cad(project: Path, out_dir: Path) -> dict:
    """Build + export through cadcode. Returns the CadcodeResult JSON."""
    python = str(VENV_PY) if VENV_PY.is_file() else sys.executable
    cmd = [python, str(CAD_CLI), str(project),
           "--out-dir", str(out_dir),
           "--wall-clock-s", str(CAD_WALL_CLOCK_S)]
    r = subprocess.run(cmd, capture_output=True, text=True,
                       timeout=CAD_WALL_CLOCK_S + 120)
    try:
        return json.loads(r.stdout.strip().splitlines()[-1])
    except (json.JSONDecodeError, IndexError):
        return {"ok": False, "error": {
            "code": "NO_JSON",
            "message": (r.stderr or r.stdout)[-500:] or "cad tool produced no output"}}


def blocking_warnings(cad: dict) -> list:
    return [f"{w.get('part', '?')}:{w.get('kind', '?')}: {w.get('detail', '')[:120]}"
            for w in (cad.get("warnings") or [])
            if str(w.get("severity", "info")).lower() in BLOCKING_SEVERITIES]


# ---------------------------------------------------------------------------
# 2. Bill of components
# ---------------------------------------------------------------------------

def load_bill(path: Path) -> list:
    """[{"name": "tile", "qty": 48}, ...] — the rules' own component list.

    Accepts either a bare list or an object with a `components` key, so the
    same file can be the idea spec or an extract from it.
    """
    raw = json.loads(path.read_text(encoding="utf-8"))
    items = raw.get("components", raw) if isinstance(raw, dict) else raw
    bill = []
    for item in items:
        name = str(item.get("name", "")).strip()
        qty = int(item.get("qty", item.get("quantity", 1)))
        if name and qty > 0:
            bill.append({"name": name, "qty": qty})
    return bill


def check_bill(bill: list, part_names: list) -> tuple[list, int]:
    """Match declared components against the parts the build actually named.

    Prefix matching, because a 48-tile bill line becomes tile_01..tile_48 in
    the assembly. Longest name first so a bill with both `tile` and
    `tile_corner` binds the specific one before the general one eats it.
    """
    total = sum(line["qty"] for line in bill)
    if not part_names:
        # cadcode collapses a single-child assembly into one unnamed model, so
        # "no named parts" means exactly one piece came out. For a one-piece
        # game that is correct and only the NAME is unverifiable; for anything
        # else it is the fusion signature — the pieces were unioned instead of
        # kept as separate named parts.
        if total == 1:
            return [], total
        return [f"bill: rules need {total} pieces across {len(bill)} kinds, but the "
                f"build exported one unnamed solid — the pieces were unioned "
                f"together instead of kept as separate named assembly children"], total

    findings = []
    unclaimed = set(part_names)
    for line in sorted(bill, key=lambda b: -len(b["name"])):
        name = line["name"]
        matched = {p for p in unclaimed
                   if p == name or p.startswith(name + "_") or p.startswith(name)}
        unclaimed -= matched
        if len(matched) != line["qty"]:
            findings.append(
                f"bill:{name}: rules need {line['qty']}, build named {len(matched)}")
    for extra in sorted(unclaimed):
        findings.append(f"bill:{extra}: part exists but no rule asks for it")
    return findings, total


# ---------------------------------------------------------------------------
# 3-5. Mesh measurement
# ---------------------------------------------------------------------------

def _bridge_span_mm(mesh) -> float:
    """Widest unsupported bridge, as inscribed-circle diameter of each
    down-facing patch. A 5mm-wide ring is a 5mm bridge no matter its diameter;
    a 50mm chamber roof is 50mm."""
    import networkx as nx
    import numpy as np

    nz = mesh.face_normals[:, 2]
    areas = mesh.area_faces
    down = np.where((nz < -0.95) &
                    (mesh.triangles_center[:, 2] > mesh.bounds[0][2] + 3.0))[0]
    if not len(down):
        return 0.0
    sel = set(down.tolist())
    g = nx.Graph((a, b) for a, b in mesh.face_adjacency if a in sel and b in sel)
    g.add_nodes_from(down.tolist())
    worst = 0.0
    for comp in nx.connected_components(g):
        comp = list(comp)
        if areas[comp].sum() < 200:  # trivial patch, not a bridge
            continue
        edges = np.sort(mesh.faces[comp][:, [0, 1, 1, 2, 2, 0]].reshape(-1, 2), axis=1)
        uniq, cnt = np.unique(edges, axis=0, return_counts=True)
        boundary = np.unique(uniq[cnt == 1])
        if not len(boundary):
            continue
        bpts = mesh.vertices[boundary][:, :2]
        cpts = mesh.triangles_center[comp][:, :2]
        d = np.sqrt(((cpts[:, None, :] - bpts[None, :, :]) ** 2).sum(-1)).min(1)
        worst = max(worst, float(2.0 * d.max()))
    return round(worst, 1)


# A part is printed in whatever orientation the owner drops it on the bed, not
# in the orientation the assembly displays it in — a lid modelled sitting on
# its box has its whole underside facing down and reads as a 58mm unsupported
# bridge, which vanishes the moment you flip it over to print. So the question
# the gate asks is the one a human asks in the slicer: is there ANY sane
# orientation in which this prints? Axis-aligned only; a part that needs an
# arbitrary tilt to print is a part the brief should have designed differently.
ORIENTATIONS = (("as-modelled", 0, 0), ("flip-X-180", 180, 0),
                ("X-90", 90, 0), ("X+90", -90, 0),
                ("Y-90", 0, 90), ("Y+90", 0, -90))


def _printability(mesh, rx: float, ry: float) -> tuple[float, float]:
    import numpy as np
    import trimesh

    m = mesh
    if rx or ry:
        m = mesh.copy()
        if rx:
            m.apply_transform(trimesh.transformations.rotation_matrix(
                np.radians(rx), [1, 0, 0]))
        if ry:
            m.apply_transform(trimesh.transformations.rotation_matrix(
                np.radians(ry), [0, 1, 0]))
    areas = m.area_faces
    nz = m.face_normals[:, 2]
    overhang = float(areas[nz < -0.7071].sum() / areas.sum() * 100.0) if areas.sum() else 0.0
    return round(overhang, 2), _bridge_span_mm(m)


def part_stats(stl: Path) -> dict:
    """Everything the gate needs to know about ONE named part.

    `bodies` is the fusion detector at the level that actually means something
    here: a named part is one manufactured piece, so a part whose mesh falls
    into several disconnected lumps cannot be printed as itself. Counting
    connected bodies on the ASSEMBLED mesh — which is what the old pipeline
    did, correctly, because the black box only ever returned one merged mesh —
    is meaningless now: parts placed touching each other in display position
    share coincident faces and merge, and the resulting open shells report
    nonsense volumes.
    """
    import trimesh

    m = trimesh.load(str(stl), force="mesh")
    split_error = None
    try:
        pieces = m.split(only_watertight=False)
    except Exception as exc:
        # Falling back to one piece is the safe assumption for everything else
        # in here, but it is also indistinguishable from a part that really is
        # one body — which would make this the quietest possible way to pass a
        # fused part. Say so instead; main() carries it into `unmeasured`.
        pieces = [m]
        split_error = f"{type(exc).__name__}: {exc}"
    bodies = max(1, len([p for p in pieces if abs(p.volume) >= MIN_BODY_VOLUME_MM3]))

    scored = []
    for label, rx, ry in ORIENTATIONS:
        overhang, bridge = _printability(m, rx, ry)
        # Prefer an orientation that clears both thresholds; among those (or
        # among all, when none clears) take the flattest bridge, then the
        # least overhang.
        passes = bridge <= BRIDGE_SPAN_MAX_MM and overhang <= OVERHANG_FAIL_PCT
        scored.append(((not passes, bridge, overhang), label, overhang, bridge))
    _, label, overhang, bridge = min(scored, key=lambda s: s[0])

    return {
        "watertight": bool(m.is_watertight),
        "bodies": bodies,
        "split_error": split_error,
        "volume_mm3": round(float(abs(m.volume)), 2),
        "bbox_mm": [round(float(x), 1) for x in (m.bounds[1] - m.bounds[0]).tolist()],
        "print_orientation": label,
        "overhang_pct": overhang,
        "bridge_span_mm": bridge,
    }


def fits_bed(bbox: list) -> bool:
    """A part may be laid down any way round on the bed, so compare sorted
    extents against the sorted usable envelope."""
    return all(part <= bed for part, bed
               in zip(sorted(bbox, reverse=True), sorted(usable_bed(), reverse=True)))


# ---------------------------------------------------------------------------
# 6. Slice
# ---------------------------------------------------------------------------

def shape_key(stats: dict) -> str:
    """Identity of a SHAPE, so 48 identical tiles slice once."""
    return f"{stats['volume_mm3']}|{stats['bbox_mm']}"


def slice_stl(stl: Path) -> dict:
    """ORCA_PROFILE = "machine.json;process.json;filament.json" (full paths)."""
    cli = os.environ.get("ORCASLICER_CLI", "").strip()
    profile = os.environ.get("ORCA_PROFILE", "").strip()
    if not cli or not profile:
        return {"sliced": None}
    parts = [p.strip() for p in profile.split(";") if p.strip()]
    if len(parts) != 3:
        return {"sliced": False, "error": "ORCA_PROFILE needs machine;process;filament"}
    with tempfile.TemporaryDirectory() as td:
        cmd = [cli, "--load-settings", f"{parts[0]};{parts[1]}",
               "--load-filaments", parts[2],
               "--slice", "0", "--outputdir", td, str(stl)]
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        except (OSError, subprocess.TimeoutExpired) as exc:
            return {"sliced": False, "error": str(exc)[:200]}
        gcodes = sorted(Path(td).glob("*.gcode"))
        if r.returncode != 0 or not gcodes:
            err = (r.stderr or r.stdout)[-200:]
            result_json = Path(td) / "result.json"
            if result_json.is_file():
                try:
                    err = json.loads(result_json.read_text()).get("error_string") or err
                except (OSError, ValueError):
                    pass
            return {"sliced": False, "error": err}
        head = gcodes[0].read_text(encoding="utf-8", errors="ignore")[:16000]
        out = {"sliced": True, "print_min": None, "filament_g": None}
        t = re.search(r"(?:estimated printing time.*?=|total estimated time:|"
                      r"model printing time:)\s*(?:(\d+)h)?\s*(?:(\d+)m)?", head, re.I)
        if t:
            out["print_min"] = int(t.group(1) or 0) * 60 + int(t.group(2) or 0)
        f = re.search(r"(?:filament used \[g\]\s*=|total filament weight \[g\]\s*:)"
                      r"\s*([\d.]+)", head, re.I)
        if f:
            out["filament_g"] = float(f.group(1))
        return out


# ---------------------------------------------------------------------------
# 7-8. Project's own checks, and graduated lessons
# ---------------------------------------------------------------------------

def load_brief(explicit: Path | None, home: Path) -> dict | None:
    """The brief for this project, if one can be found.

    A project lives at <slug>/project/ with its brief a level up at
    <slug>/brief.json, so that is the default; the project's own directory is
    searched first so a self-contained fixture needs no flag.
    """
    candidates = [explicit] if explicit else [home / "brief.json",
                                              home.parent / "brief.json"]
    for path in candidates:
        if path and path.is_file():
            try:
                return json.loads(path.read_text(encoding="utf-8"))
            except (OSError, ValueError):
                return None
    return None


def run_fit_checks(project: Path) -> tuple[str | None, bool]:
    """The builder's own interface checks. Absent is a finding in its own
    right: a brief with an `## Interfaces` section and no fit_checks.py means
    nothing ever verified that the pieces fit the holes."""
    script = (project if project.is_dir() else project.parent) / "fit_checks.py"
    if not script.is_file():
        return None, True
    python = str(VENV_PY) if VENV_PY.is_file() else sys.executable
    r = subprocess.run([python, str(script)], capture_output=True, text=True,
                       timeout=300, cwd=script.parent)
    if r.returncode == 0:
        return "pass", True
    return (r.stdout + r.stderr)[-300:], False


# Each entry is a lesson that has already cost real builds. Prose in
# lessons.md is where a lesson starts; this list is where it ends up once it
# has repeated. improve.py may add rows here — through a PR.
#
# The first field is the rule's id, and it is load-bearing rather than
# decorative: lessons.md points at exactly this string, and
# graduation_check.py fails if it stops existing. Without an id a graduation
# could only claim "LINT_RULES exists", which stays true after the rule itself
# has been deleted. Never rename one without moving the marker with it.
LINT_RULES = [
    ("blanket-fillet",
     re.compile(r"\.edges\(\s*\)\s*\.(fillet|chamfer)\("),
     "blanket .edges().fillet/chamfer — OCCT synthesises a spherical vertex "
     "blend at every corner and tessellates it into phantom sliver bodies. "
     "Bake corner rounds into the 2D profile, or use directional selectors "
     "('|Z', '>Z')."),
]


def lint_source(project: Path) -> list:
    files = [project] if project.is_file() else [
        p for p in project.rglob("*.py") if "__pycache__" not in p.parts]
    issues = []
    for path in files:
        src = path.read_text(encoding="utf-8", errors="ignore")
        for rule_id, pattern, message in LINT_RULES:
            if pattern.search(src):
                issues.append(f"lint:{path.name}:{rule_id}: {message}")
    return issues


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("project", type=Path, help="project dir or generator .py")
    ap.add_argument("--bill", type=Path,
                    help="component bill JSON; without it the piece-count "
                         "checks are reported but cannot fail the gate")
    ap.add_argument("--brief", type=Path,
                    help="brief.json; defaults to the project dir then its "
                         "parent. Read only to find parts declared to move.")
    ap.add_argument("--no-slice", action="store_true")
    ap.add_argument("--out", type=Path, help="default <project>/gate.json")
    args = ap.parse_args()

    project = args.project.resolve()
    home = project if project.is_dir() else project.parent
    out_path = args.out or (home / "gate.json")
    report: dict = {"project": str(project),
                    "source_sha256": source_fingerprint(project),
                    "bed_usable_mm": list(usable_bed())}
    fails: list = []
    # Everything a check wanted to look at and could not. Never merged into
    # `fails` — see the module docstring — and never dropped either.
    unmeasured: list = []

    # 1. build
    build_dir = home / "build"
    cad = run_cad(project, build_dir)
    report["build"] = {"ok": bool(cad.get("ok")),
                       "is_solid": cad.get("is_solid"),
                       "volume_mm3": cad.get("volume_mm3")}
    if not cad.get("ok"):
        err = cad.get("error") or {}
        report["build"]["error"] = f"{err.get('code', '?')}: {err.get('message', '')[:300]}"
        report["pass"] = False
        report["fails"] = [f"build_failed: {report['build']['error']}"]
        # Always present, so a reader never has to tell "measured nothing"
        # apart from "an older gate.json that had no such field".
        report["unmeasured"] = unmeasured
        out_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
        print("GATE FAIL " + json.dumps({"fails": report["fails"]}))
        return 1

    blocking = blocking_warnings(cad)
    fails += [f"cad:{w}" for w in blocking]
    report["build"]["blocking_warnings"] = blocking

    # 2. bill
    parts = cad.get("parts") or []
    part_names = [str(p.get("name", "")) for p in parts]
    report["part_count"] = len(parts) or 1
    expected_total = None
    if args.bill and args.bill.is_file():
        bill = load_bill(args.bill)
        bill_fails, expected_total = check_bill(bill, part_names)
        fails += bill_fails
        report["bill"] = {"expected_total": expected_total, "findings": bill_fails}

    # 3-5. per-part: one piece, closed, on the bed, printable in some orientation
    assembled = Path(cad["stl_path"])
    stls = [(str(p.get("name")), Path(p["stl_path"])) for p in parts if p.get("stl_path")]
    if not stls:
        stls = [("model", assembled)]
    seen: dict[str, str] = {}
    report["parts"] = {}
    for name, stl in stls:
        if not stl.is_file():
            fails.append(f"artifact:{name}: no STL exported")
            continue
        stats = part_stats(stl)
        report["parts"][name] = stats
        if stats.get("split_error"):
            unmeasured.append(f"pieces:{name}: the mesh could not be split into "
                              f"bodies ({stats['split_error']}), so it was counted "
                              f"as one — a fused part would look identical")
        if stats["bodies"] != 1:
            fails.append(f"pieces:{name}: one named part but {stats['bodies']} "
                         f"disconnected bodies — cannot be printed as one piece")
        if not stats["watertight"]:
            fails.append(f"watertight:{name}: mesh is not closed")
        if not fits_bed(stats["bbox_mm"]):
            bx, by, bz = stats["bbox_mm"]
            mx, my, mz = usable_bed()
            fails.append(f"envelope:{name}: {bx}x{by}x{bz}mm does not fit the usable "
                         f"bed {mx}x{my}x{mz}mm in any orientation — split it")
        if stats["overhang_pct"] > OVERHANG_FAIL_PCT:
            fails.append(f"overhang:{name}: {stats['overhang_pct']}% down-facing "
                         f"even in its best orientation ({stats['print_orientation']})")
        if stats["bridge_span_mm"] > BRIDGE_SPAN_MAX_MM:
            fails.append(f"bridge:{name}: {stats['bridge_span_mm']}mm unsupported span "
                         f"> {BRIDGE_SPAN_MAX_MM}mm even in its best orientation "
                         f"({stats['print_orientation']})")
        seen.setdefault(shape_key(stats), name)

    # 6. interference between placed pieces. Wrapped because this is the one
    # check that reads the assembled mesh rather than the per-part exports, and
    # a gate that cannot reach a verdict is worse than one that reports it could
    # not measure something.
    try:
        from interference import check_interference, load_motions, unswept_moving_parts

        motions = load_motions(home / "motion.json")
        interference = check_interference(
            assembled,
            dict(stls),
            expected_components=expected_total,
            motions=motions,
        )
        fails += interference["findings"]
        report["interference"] = interference
        unmeasured += [f"interference: {note}"
                       for note in interference.get("inconclusive") or []]

        # A part the brief says moves, that no motion sweeps, was passed on a
        # pose nothing ever questioned. Forgetting the declaration has to cost
        # what failing it costs, or saying nothing is the cheapest way through.
        brief = load_brief(args.brief, home)
        unswept = unswept_moving_parts(brief, motions)
        report["interference"]["unswept_moving_parts"] = unswept
        fails += [
            f"motion:{part}: the brief declares it turns or slides, but "
            f"motion.json does not sweep it — a pass here would be about a "
            f"motion nothing looked at"
            for part in unswept
        ]
    except Exception as exc:
        note = f"check did not run: {type(exc).__name__}: {exc}"
        report["interference"] = {"inconclusive": [note]}
        unmeasured.append(f"interference: {note}")

    # 7. slice, once per distinct shape
    report["distinct_shapes"] = len(seen)
    if not args.no_slice:
        sliced = {}
        by_name = dict(stls)
        for key, name in seen.items():
            result = slice_stl(by_name[name])
            sliced[name] = result
            if result.get("sliced") is False:
                fails.append(f"slice:{name}: {result.get('error', 'slicer failed')}")
        report["slice"] = sliced
        # One line for the whole run, not one per shape. The information is
        # identical either way and the twelve-line version is the kind of noise
        # that teaches an owner to skim past the section that matters.
        skipped = [name for name, r in sliced.items() if r.get("sliced") is None]
        if skipped:
            unmeasured.append(
                f"slice: no slicer configured (ORCASLICER_CLI / ORCA_PROFILE), so "
                f"none of the {len(skipped)} distinct shape(s) was put through it — "
                f"nothing here knows they slice, or how long they take to print")
    else:
        unmeasured.append("slice: --no-slice, so no shape was put through the "
                          "slicer and no print time is known")

    # 8. fit checks
    fit, fit_ok = run_fit_checks(home)
    report["fit_checks"] = fit if fit is not None else "absent"
    if not fit_ok:
        fails.append("fit_checks: failed")

    # 9. lint
    fails += lint_source(project)

    report["pass"] = not fails
    report["fails"] = fails
    # Not a fail, but never silent: a pass that could not measure something has
    # to say so, or "GATE PASS" means less than it looks like it means. This is
    # the field pipeline_queue.py reads on `advance` and refuses to `ship` on,
    # so it is a top-level key rather than something a reader has to go digging
    # for inside one check's sub-report.
    report["unmeasured"] = unmeasured
    out_path.write_text(json.dumps(report, indent=2), encoding="utf-8")
    summary = {"parts": report["part_count"],
               "expected": expected_total,
               "distinct_shapes": report["distinct_shapes"],
               "fails": fails}
    if unmeasured:
        summary["unmeasured"] = unmeasured
    print(("GATE PASS " if report["pass"] else "GATE FAIL ") + json.dumps(summary))
    return 0 if report["pass"] else 1


if __name__ == "__main__":
    sys.exit(main())
